# Generated by Django 3.1.2 on 2020-11-18 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UniChatApp', '0003_groupchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='member',
        ),
        migrations.AddField(
            model_name='groupchat',
            name='member',
            field=models.ManyToManyField(related_name='_groupchat_member_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
