# Generated by Django 3.1.2 on 2020-11-22 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UniChatApp', '0004_auto_20201118_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='title',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField()),
                ('message', models.CharField(max_length=1000)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniChatApp.language')),
                ('linkedFriendList', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniChatApp.friendlist')),
                ('linkedGroupchat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniChatApp.groupchat')),
            ],
        ),
    ]
